### ISSUE TITLE
Not showing wallet balance 

### ISSUE THREAD

**Issue by shanhashcah** [binance/binance-futures-connector-java#18]
I am using /fapi/v2/account API to get account information but I am getting only USDT balance and rest of the balance  are showing zero. Moreover I have recently traded XRPUSDT, my USDT balance get changed but XRP balance is still showing zero.

Thanks

**Comment by 2pd** [comment]
Could you please check what's the futures account balance from UI, this method in the library doesn't parse the result from server, but return exactly what's received.
