### ISSUE TITLE
UMWebsocketClientImpl.allMarkPriceStream() occured 'NoSuchMethodError' when using 'binance-connector-java' together

### ISSUE THREAD

**Issue by yechanpark** [binance/binance-futures-connector-java#3]
hi. im using libraries both [binance-futures-connector-java](https://github.com/binance/binance-futures-connector-java) and [binance-connector-java](https://github.com/binance/binance-connector-java) in one spring boot project with kotlin.

when i write following test code, `NoSuchMethodError` has been occured.
and success when excluded 'binance-connector-java'.

 - build.gradle.kts
```kotlin
dependencies {
	...

	// https://mvnrepository.com/artifact/io.github.binance/binance-connector-java
	implementation("io.github.binance:binance-connector-java:1.12.0")

	// https://mvnrepository.com/artifact/io.github.binance/binance-futures-connector-java
	implementation("io.github.binance:binance-futures-connector-java:1.0.0")
}
```

 - test code
```kotlin
import com.binance.connector.client.impl.UMWebsocketClientImpl
import com.binance.connector.client.utils.WebSocketCallback
// ...

class Test {
    @Test
    fun subscribe() {

        val callback = WebSocketCallback {
            println(it)
        }
        // NoSuchMethodError
        // success when excluded 'binance-connector-java'
        UMWebsocketClientImpl().allMarkPriceStream(
            3, callback
        )

        sleep(1000 * 10)
    }
}
```

`java.lang.NoSuchMethodError: 'java.lang.String com.binance.connector.client.impl.UMWebsocketClientImpl.getBaseUrl()'`
or
`java.lang.NoSuchMethodError: 'com.binance.connector.client.utils.WebSocketCallback com.binance.connector.client.impl.UMWebsocketClientImpl.getNoopCallback()`

can i fix this without copy & paste?

im not sure, but i guess the reason of this is many classes and enums are placed in both libraries as same package but has difference properties.

i copied & pasted code in my different package (ex. `com.binance.futures.connector.~` ) because of this error and handling it my self.

**Comment by aisling-2** [comment]
This is handled in the new version 2.0.0. Thank you.
