### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by Holobar** [binance/binance-futures-connector-java#5]
When I use the command mvn install, I get a build failure:
Tests in error:
  testNewOrder(unit.cm_futures.account.TestCMNewOrder)
  testNewOrder(unit.um_futures.account.TestUMNewOrder)
  
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project binance-futures-connector-java: There are test failures.

Thanks for any feedback about this issue!

**Comment by jonte-z** [comment]
Hi, can you please confirm that you're no longer encountering this issue now?

**Comment by programer19** [comment]
I've got the same error now.
Results :

Failed tests:   testBuildFullUrl(unit.TestUrlBuilder): expected:<...value1&key2=2&key3=0[.]0006> but was:<...value1&key2=2&key3=0[%2C]0006>
  testJoinLargeQueryParameters(unit.TestUrlBuilder): expected:<...value1&key2=2&key3=0[.0006&key4=0.]00000000000000000000...> but was:<...value1&key2=2&key3=0[%2C0006&key4=0%2C]00000000000000000000...>
  testJoinQueryParameters(unit.TestUrlBuilder): expected:<...value1&key2=2&key3=0[.]0006> but was:<...value1&key2=2&key3=0[%2C]0006>

Tests in error: 
  testNewOrder(unit.cm_futures.account.TestCMNewOrder)
  testNewOrder(unit.um_futures.account.TestUMNewOrder)

**Comment by programer19** [comment]
> I've got the same error now.
> 
> ```
> Results :
> 
> Failed tests:   testBuildFullUrl(unit.TestUrlBuilder): expected:<...value1&key2=2&key3=0[.]0006> but was:<...value1&key2=2&key3=0[%2C]0006>
>   testJoinLargeQueryParameters(unit.TestUrlBuilder): expected:<...value1&key2=2&key3=0[.0006&key4=0.]00000000000000000000...> but was:<...value1&key2=2&key3=0[%2C0006&key4=0%2C]00000000000000000000...>
>   testJoinQueryParameters(unit.TestUrlBuilder): expected:<...value1&key2=2&key3=0[.]0006> but was:<...value1&key2=2&key3=0[%2C]0006>
> 
> Tests in error: 
>   testNewOrder(unit.cm_futures.account.TestCMNewOrder)
>   testNewOrder(unit.um_futures.account.TestUMNewOrder)
> ```

the problem might be with default locale (which in my case is ru_RU.UTF-8). The moment I ran it as `LANG=en_US.UTF-8 mvn install` the problem gone

**Comment by aisling-2** [comment]
Hi @Holobar @programer19,
This issue is related to the decimal format being different in the various locations where the requests are executed.
It's now fixed in the [latest `v3.0.4`](https://github.com/binance/binance-futures-connector-java/releases/tag/v3.0.4.
