### ISSUE TITLE
Implement HTTP Proxy for binance-futures-connector-java

### ISSUE THREAD

**Issue by linuradu** [binance/binance-futures-connector-java#8]
Would be great if there will be implemented support for HTTP Proxy.

There is already implemented for binance-futures-connector-python and for [GitHub - binance/binance-connector-java](https://github.com/binance/binance-connector-java).

If there is no time for this feature, can I register as a contributor and implement this feature?

Best regards,
Radu Linu

**Comment by linuradu** [comment]
I created a pull request for this missing feature: https://github.com/binance/binance-futures-connector-java/pull/9

**Comment by andreipetrascu** [comment]
Hi @jonte-z, @aisling-2, @2pd, @bnbot!
I see this open issue as an amazing feature that can be added to the current system.
When is it estimated to be ready for use?
Many thanks!

**Comment by jonte-z** [comment]
Hi all,

HTTP Proxy support has now been implemented in v3.0.0 which was just pushed.

Regards,
